image: Visual Studio 2019 Preview
version: 5.0.0-{build}
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    NPGSQL_TEST_DB: Host=localhost;Database=postgres;Username=postgres;Password=Password12!
    PGUSER: postgres
    PGPASSWORD: Password12!
    POSTGIS_EXE: postgis-bundle-pg11x64-setup-2.5.3-1.exe
    NoPackageAnalysis: true  # Suppresses warning about SemVer 2.0.0 version suffixes when packing
cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - 'C:\projects\npgsql\packages -> **\*.csproj'  # For VSIX
  - $(POSTGIS_EXE)
clone_depth: 10
install:
  - powershell .build\setup_appveyor.ps1
  # The following can be used to install a custom version of .NET Core
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1" -OutFile "install-dotnet.ps1"
  - ps: .\install-dotnet.ps1 -Version 3.1.100 -InstallDir "dotnetcli"
services:
  - postgresql111
before_build:
  - '"C:\Program Files\PostgreSQL\11\bin\psql" -c "CREATE EXTENSION citext"'
  - '"C:\Program Files\PostgreSQL\11\bin\psql" -c "CREATE EXTENSION postgis"'
  - appveyor-retry dotnet restore -v Minimal Npgsql.sln
  - appveyor-retry msbuild src\VSIX\VSIX.csproj /t:Restore /v:Minimal
build_script:
  - dotnet build "test\Npgsql.Tests" -c Debug
  - dotnet build "test\Npgsql.PluginTests" -c Debug
  - dotnet build "test\Npgsql.Specification.Tests" -c Debug
  - dotnet build "src\Npgsql" -c Release
  - msbuild src\VSIX\VSIX.csproj /p:Configuration=Release /v:Minimal
  - msbuild src\MSI\MSI.wixproj /p:Configuration=Release /v:Minimal
after_build:
  - dotnet pack src\Npgsql\Npgsql.csproj -c Release
  - dotnet pack src\Npgsql.Json.NET\Npgsql.Json.NET.csproj -c Release
  - dotnet pack src\Npgsql.NodaTime\Npgsql.NodaTime.csproj -c Release
  - dotnet pack src\Npgsql.LegacyPostgis\Npgsql.LegacyPostgis.csproj -c Release
  - dotnet pack src\Npgsql.RawPostgis\Npgsql.RawPostgis.csproj -c Release
  - dotnet pack src\Npgsql.NetTopologySuite\Npgsql.NetTopologySuite.csproj -c Release
test:
  assemblies:
    - test\Npgsql.Tests\bin\Debug\net461\Npgsql.Tests.dll
    - test\Npgsql.PluginTests\bin\Debug\net461\Npgsql.PluginTests.dll
    - test\Npgsql.Specification.Tests\bin\Debug\net461\Npgsql.Specification.Tests.dll
    - test\Npgsql.Tests\bin\Debug\netcoreapp3.1\Npgsql.Tests.dll
    - test\Npgsql.PluginTests\bin\Debug\netcoreapp3.1\Npgsql.PluginTests.dll
    - test\Npgsql.Specification.Tests\bin\Debug\netcoreapp3.1\Npgsql.Specification.Tests.dll
artifacts:
  - path: 'src\**\*.nupkg'
    name: Nuget
  - path: 'src\**\*.snupkg'
    name: Nuget symbol packages
  - path: 'src\VSIX\bin\**\*.vsix'
    name: Visual Studio Extension
  - path: 'src\MSI\bin\**\*.msi'
    name: MSI Installer
deploy:
  - provider: Environment
    name: MyGet Unstable
    on:
      deploy_myget_unstable: true
  - provider: Environment
    name: MyGet Stable
    on:
      deploy_myget_stable: true
  - provider: Environment
    name: Npgsql Github
    on:
      deploy_github_release: true
