language: csharp
dist: trusty
sudo: false
mono: none
dotnet: 2.0.0-preview1-005977

services:
  - postgresql
addons:
  postgresql: "9.6"

env:
  - NPGSQL_TEST_DB: '"Host=localhost;Database=npgsql_tests;Username=npgsql_tests;Password=npgsql_tests"'

before_script:
  - psql -U postgres -c "CREATE USER npgsql_tests PASSWORD 'npgsql_tests' SUPERUSER"
  - psql -U postgres -c "CREATE DATABASE npgsql_tests OWNER npgsql_tests"
  - psql -U postgres -c "CREATE EXTENSION postgis" npgsql_tests
  - dotnet restore -v Minimal
script:
  - dotnet build "test/Npgsql.Tests" -c Debug -f netcoreapp2.0
  - dotnet test "test/Npgsql.Tests/Npgsql.Tests.csproj" -c Debug -f netcoreapp2.0

cache:
  directories:
    - $HOME/.nuget/packages

# The following is necessary because of https://github.com/travis-ci/travis-ci/issues/6972
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

