version: '3'

services:
  npgsql-dev:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    volumes:
      - ..:/workspace:cached
    tty: true
    links: 
      - db

  db:
    build: ./db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports: 
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./pgadmin_files:/var/lib/pgadmin
    ports:
      - 5050:5050
    links:
      - db
